import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";
import MainContent from "../components/MainContent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-screen  min-h-screen">
        <Sidebar />
        <div className="flex-1 max-w-[100%]">
          <MainContent />
        </div>
      </div>
    </>
  );
}
